### ISSUE TITLE
Facemask (08JAN20212) air is directed onto face

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#10]
Nose gets really cold and chapstick is required for lips

**Comment by mmroden** [comment]
Closed by #31 with the grommet
![Screen Shot 2021-02-03 at 9 44 08 AM](https://user-images.githubusercontent.com/116251/106787302-67a98f80-6604-11eb-9c59-9a2f3a9429eb.png)
