### ISSUE TITLE
Black wall on M12 controller at 2 layers blocks LED

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#115]
Current limiting resistor for LED swapped out to 100 ohms, LED is driven at 18mA

![image](https://user-images.githubusercontent.com/57600622/114285761-82d2ba00-9a0e-11eb-9980-f17b965ff4eb.png)

**Comment by mmroden** [comment]
Not a problem for the pink papr

**Comment by mmroden** [comment]
not a problem for grey-- blue may not shine through black very well?  Maybe spec a brighter LED?

**Comment by mmroden** [comment]
we do need to spec the specific LED.  Don't have a problem with superbrights, because have to go through plastic.  Didn't matter with direct exposure with the light pipe, but now that the light pipe is encased in plastic, should use superbrights

**Comment by mmroden** [comment]
targeting a red LED

**Comment by mmroden** [comment]
red LEDs are hard to get right now, may have to look at a different color.

**Comment by mechatroniks-git** [comment]
Blue LED: https://www.we-online.de/katalog/datasheet/150080BS75000.pdf
With 100ohm LEDs, we were driving the led at about 18mA, which is about 135mcd. These LEDs have a 140° viewing angle, which is close to the 160° recommended [here](https://vcclite.com/light-pipe-faqs/#:~:text=For%20ideal%20illumination%20whether%20using,viewing%20angle%20of%20160%20degrees.). 

![image](https://user-images.githubusercontent.com/57600622/114432034-11f9e200-9b75-11eb-9d3f-eead7bcc7caa.png)

**Comment by mechatroniks-git** [comment]
Recommend using this [JLC LED](https://lcsc.com/product-detail/Light-Emitting-Diodes-LED_Foshan-NationStar-Optoelectronics-NCD0603G1_C84267.html) see [datasheet](https://datasheet.lcsc.com/szlcsc/2008201032_Foshan-NationStar-Optoelectronics-NCD0603G1_C84267.pdf)

**Comment by mechatroniks-git** [comment]
![image](https://user-images.githubusercontent.com/57600622/115945319-07dabc00-a470-11eb-99ba-f84884c18192.png)

**Comment by mmroden** [comment]
Don't print it in black; make sure to document
