### ISSUE TITLE
BNC on PCB nuts require 9/16" nut driver, 14mm was used successfully

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#116]

**Comment by mmroden** [comment]
Will have to spec this out, there are two different sizes-- box is 5/8, controller is 15mm, so maybe have to get more compatible parts?

**Comment by mmroden** [comment]
have to order a separate nut for what goes on the board, not sure if we can find one that fits that threading.

**Comment by mmroden** [comment]
Documentation issue to make sure we capture the proper nut drivers.  Need a deep socket set or an adjustable wrench

**Comment by mmroden** [comment]
Moved to docs repo
