### ISSUE TITLE
PCB connector placement in M12 Controller Body and Controller Plate can be off

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#13]
Due to tolerances of the assembly (without a soldering fixture), connectors don't easily fit in housing

**Comment by mechatroniks-git** [comment]
@DHHwangPhD I would recommend slotting the DC power jacks to allow for board misalignment. Slotting it by 1mm total (.5mm left to right) should be sufficient and still be covered by the washer & nut. 

![image](https://user-images.githubusercontent.com/57600622/105612138-ebdf5580-5d6e-11eb-8595-10ab72b035c8.png)

![image](https://user-images.githubusercontent.com/57600622/105612166-25b05c00-5d6f-11eb-808f-4bdf32b331ca.png)

**Comment by DHHwangPhD** [comment]
Done in v18 of the M12 PAPRA Controller

**Comment by mmroden** [comment]
![image (23)](https://user-images.githubusercontent.com/116251/106786294-3da39d80-6603-11eb-92af-1b831b5ccdbc.png)
Solved in #31 with updated holes on the bottom of the controller, as well as with the updated lid
![image (24)](https://user-images.githubusercontent.com/116251/106786357-501dd700-6603-11eb-81e5-c910e5ffef43.png)
