### ISSUE TITLE
Fan Box Assembly Diagram

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#131]
Need a fan box assembly diagram for the documentation

**Comment by argus1** [comment]
seems to be misalignment of the screw holes for the fanbox and the base plate, is user-rescale is required?

**Comment by mmroden** [comment]
Which misalignment are you seeing?  Maybe a picture to show the problem?

**Comment by argus1** [comment]
nevermind, I think my printer shrunk the baseplate, I would scale down the box, but likely the fan won't fit after that.

**Comment by mmroden** [comment]
closed by #147
