### ISSUE TITLE
People complain that masks hit them on the chin

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#149]
People are complaining that the masks hit them on the chin; they expect the mask to go under the chin, like a cloth mask.  Just something to think about viz designs.

**Comment by MarkPorter66** [comment]
is this a real issue?

**Comment by mmroden** [comment]
Well, they don't want to wear the masks, so...

**Comment by mmroden** [comment]
Closing because we know we need better/different masks
