### ISSUE TITLE
Make a BOM

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#15]

**Comment by mechatroniks-git** [comment]
See: https://docs.google.com/spreadsheets/d/1SvVoTHTWQuhzA31efnyqhaFsMOlKPyU90ATQrHQNn1k/edit#gid=0

**Comment by mmroden** [comment]
Stuff at the bottom is not defined, respirator needs part numbers

**Comment by mmroden** [comment]
Have one for the 29 Jan version, need a copy to be for the next build party

**Comment by mechatroniks-git** [comment]
@Burhan-Q can you assign part numbers to the respirator parts? I setup https://github.com/tetrabiodistributed/tetraPLM so anyone can create a new part number

**Comment by Burhan-Q** [comment]
Reserved for respirator components:

P-TET-000-118-0
P-TET-000-119-0
P-TET-000-120-0
P-TET-000-121-0
P-TET-000-122-0

**Comment by mmroden** [comment]
webbing and triglides need to get finished

**Comment by mechatroniks-git** [comment]
BOM created, waiting on PR merge - https://github.com/tetrabiodistributed/tetraPLM/pull/2

**Comment by mmroden** [comment]
reached out to @sharpybynature to see if we can get Helpful help here

**Comment by mmroden** [comment]
https://erpnext.com/open-source-manufacturing-erp-software

**Comment by mechatroniks-git** [comment]
We need to install it on our own git https://github.com/frappe/erpnext

**Comment by DHHwangPhD** [comment]
@mechatroniks-git @mmroden @darraghbr @capsulecorplab  BOM spreadsheet is incorrect on the parts that need to be printed. M12 parts are older models. Needs updating. Will bring up at Saturday meeting.

**Comment by mmroden** [comment]
BOM was updated
