### ISSUE TITLE
Check a fan taper to see if it will work with this model fan

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#150]
Design the taper for testing to see if we can get to the 4 CFM requirement

https://www.digikey.co.uk/product-detail/en/sunon-fans/PF97331B1-B00U-A99/259-1925-ND/6189086

or

https://www.cuidevices.com/product/thermal-management/dc-fans/centrifugal-blowers/cbm-97b-series

**Comment by mechatroniks-git** [comment]
Snapshot of distributor stock:

![image](https://user-images.githubusercontent.com/57600622/121054104-df352a00-c770-11eb-8ad8-6fcc30c8b1ac.png)

![image](https://user-images.githubusercontent.com/57600622/121054266-0986e780-c771-11eb-866c-9768001609bb.png)

**Comment by darraghbr** [comment]
https://www.digikey.co.uk/product-detail/en/delta-electronics/BFB1012EH-A/603-2105-ND/9351771

**Comment by mechatroniks-git** [comment]
![image](https://user-images.githubusercontent.com/57600622/121056418-0856ba00-c773-11eb-8b32-5ace90db73b5.png)

**Comment by mechatroniks-git** [comment]
Results from testing. Blower inlet to open air, short cone "TestFunnelShort" taped to blower with 36 inches of blue hose to Sensirion to open air. 

![image](https://user-images.githubusercontent.com/57600622/122790531-407af400-d26d-11eb-8b12-470a48128274.png)

All 3 blowers would require a 11V minimum to meet 4CFM. The M12 battery will start at 12.4V and drain down to 8.4V, making the CUI CBM-120B series a better fit with our battery and electronics. See [prior test](https://github.com/tetrabiodistributed/papr-print-files/issues/151#issuecomment-856045012)

**Comment by mmroden** [comment]
This work is done, we know we need to hit 4CFM
