### ISSUE TITLE
Test the fan taper to ensure that 4 CFM is hit

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#151]
blocked on #150 ; once we have a fan taper, we can then redesign the box for the fan

**Comment by mechatroniks-git** [comment]
**Airflow tests with OLD funnel**

NMB BG1203-B045-00S FAN + FUNNEL + 36" BLUE HOSE + FLOW SENSOR
12V | .44A | 52SLM

**Airflow tests with NEW funnel**

NMB BG1203-B045-00S FAN + FUNNEL + 36" BLUE HOSE + FLOW SENSOR
12V | .51A | 70SLM

UTUO FAN + FUNNEL + 36" BLUE HOSE + FLOW SENSOR
12V | .33A | 60SLM

We see improvement, but not enough to hit the target

**Comment by mechatroniks-git** [comment]
Tested the CUI blower without disassembling (in fan box with HEPA filter) using the legacy funnel as attached. 

We able to get 4CFM easily at around 8V & 2A.  Could be a drop in solution to our challenges. The voltage range matches up with the M12 battery and controller electronics. 

![image](https://user-images.githubusercontent.com/57600622/121046172-c88bd480-c76a-11eb-99ef-a2ed09f9e7bf.png)

**Comment by mmroden** [comment]
This is done in the sense that we know the answer; the taper has been defined and models must be made
