### ISSUE TITLE
SPIKE: explore AAF filter material

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#153]
Check to see if AAF has a filter that we can use:
https://www.aafintl.com/en/commercial/browse-products/commercial/hepa-ulpa-filters

**Comment by argus1** [comment]
using the following DIMENSIONS 6.29 x 3.97 x 0.78 in

**Comment by argus1** [comment]
AAF relays that MegaCel II ePTFE has a thickness of 50mm for optimal filtration

**Comment by argus1** [comment]
following up to see if further adaptation is possible
