### ISSUE TITLE
Investigate new BNC cables

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#158]
Need to update the BNC cables in the BOM to reflect the proper gauge for the power draw

**Comment by mechatroniks-git** [comment]
Options:
20 awg - https://www.jameco.com/z/205-523-Steren-Electronics-Cable-Assembly-RG58-U-36-Bnc-To-Bnc-50-Ohm_11404.html


26 awg (rated for 2.2A)- https://www.jameco.com/z/G7402-R-Jameco-Valuepro-Cable-Assembly-Rg174-U-3-BNC-to-BNC-50-Ohm_111473.html

**Comment by mmroden** [comment]
Kevin to help review

**Comment by mmroden** [comment]
"V-MCM-6641T11	" will be tested

**Comment by mmroden** [comment]
New BNC cable worked.

**Comment by mmroden** [comment]
Apparently "plug it in and it works" isn't enough.  My bad.

**Comment by mechatroniks-git** [comment]
@DHHwangPhD Which BNC did you order from McMaster?
Either one of these would work
![image](https://user-images.githubusercontent.com/57600622/134041740-20b72ee5-9e09-42e2-8244-69c03c1a2762.png)

From [Engineering Toolbox](https://www.engineeringtoolbox.com/wire-gauges-d_419.html), we're good to 5A

![image](https://user-images.githubusercontent.com/57600622/134042555-58e94f44-0f9f-4724-93da-d7d71c5b5a69.png)

**Comment by mmroden** [comment]
max amperage we have in current models is 1.3-1.4, so maybe target 2 amps so we have a lot of breathing room.

22 gauge should be more than fine, 24 gauge should also be OK if we can find it.

RG-59/U will work.
