### ISSUE TITLE
eFuse tripping when run at lower amperage

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#167]
When the fan box is run at less than full amperage (not 2.8, but around 2.2), the efuse trips.  At this amperage, the fan box will cycle between being on and off.

**Comment by mmroden** [comment]
Parts are ordered, gonna build those out.

**Comment by mechatroniks-git** [comment]
Testing/evaluation
1. Test trip current 
2. Test undervoltage 
3. Test overvoltage
4. Test reverse polarity
5. Test fuse thru full PWM range at PWM freq, using highest current draw blower

**Comment by mmroden** [comment]
Resolved by the current papra-pcb.
