### ISSUE TITLE
Investigate 30mm hosing to determine if that will relieve the battery life pressure

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#170]
30mm hoses that split to 2 22mm hoses may work well for more flow coming out of the system

**Comment by darraghbr** [comment]
I've done some quick calculations and I think we would see between 2 and 5% flow rate increase moving from a 22mm to a 30mm hose, depending on the fan

[30mm hose airflow.pdf](https://github.com/tetrabiodistributed/papr-print-files/files/7209636/30mm.hose.airflow.pdf)
.

**Comment by mmroden** [comment]
Here is the hosing to buy: https://www.mcmaster.com/hose/id~30mm/

**Comment by mmroden** [comment]
3d crowd did this testing, Mark Porter will need to provide

**Comment by mmroden** [comment]
This did not seem to work.
