### ISSUE TITLE
Ninjaflex mask ("FitMaskBody.stl") has an internal lip that is a bit sharp

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#18]
![Image from iOS (2)](https://user-images.githubusercontent.com/116251/105079782-c2f45300-5a44-11eb-9e04-afff3df0c84a.jpg)
This internal lip is a bit sharp and prone to printing errors when printed with supports (which have to be used)

![Image from iOS (3)](https://user-images.githubusercontent.com/116251/105079825-d69fb980-5a44-11eb-812a-1d6ea4f8013b.jpg)
This rip comes from the Prusa slicer supports being removed

**Comment by Burhan-Q** [comment]
Cross section view of mask at the highest point of the nose region
![image](https://user-images.githubusercontent.com/62214284/105610557-2b616e00-5d7e-11eb-8a93-9da974bce0ac.png)

**Comment by mmroden** [comment]
the image of my cut-up face
![Uploading Image from iOS (3).jpg…]()

**Comment by mmroden** [comment]
Solved from #31 
![Image from iOS (5)](https://user-images.githubusercontent.com/116251/106786753-c4587a80-6603-11eb-894d-6b242aa037f4.jpg)
