### ISSUE TITLE
3M respirator adapter not properly mounting

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/papr-print-files#192]
The 3M respirator adapter has issues clipping and staying onto [3M half facepiece reusable respirator mask](https://www.amazon.com/3M-Respirator-6300-Respiratory-Protection/dp/B007JZ1MK6/)
![2021-10-24 17 18 41](https://user-images.githubusercontent.com/14095576/154133057-40bc77a1-0fdd-4901-9d49-3dbe8b9a735b.jpg)
![2021-10-24 17 19 20](https://user-images.githubusercontent.com/14095576/154133065-b7760f09-768a-410a-9b68-a2c487ac5e67.jpg)
![2021-10-24 17 20 38](https://user-images.githubusercontent.com/14095576/154133075-2eb59c56-7197-4cf0-8636-2b45eb30bd14.jpg)

**Comment by mmroden** [comment]
Closed by #212, the attachment points come through the side with no source control (yet!)
