### ISSUE TITLE
The pressure tap model needs to get built

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#220]
I've got a pull request set up for the pressure tap setup, but unfortunately, Prusa Slicer won't remove negative spaces.  So, I need someone to remove the negative spaces as per the attached image (ie, only about a mm thickess)

![PXL_20221012_003032320](https://user-images.githubusercontent.com/116251/195227980-eee2d1ba-cc21-4154-917a-52ae228ced53.jpg)

**Comment by mmroden** [comment]
[Pressure Tap v3.zip](https://github.com/tetrabiodistributed/papr-print-files/files/9792716/Pressure.Tap.v3.zip)
Here is the 3mf file that is the source

**Comment by Judoguy12** [comment]
I have no thin walls on my slicer although it appears to be very thin walls so would be better suited to resin

**Comment by mmroden** [comment]
@DHHwangPhD has an updated model for this, would need a PR to close using that model with a new part number.  I may just do that right now

**Comment by mmroden** [comment]
Closed by #224
