### ISSUE TITLE
Exploded diagram for the fan box for the Jan 2021 version of the PAPRa

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#27]
Need an exploded diagram of the fan box

**Comment by mmroden** [comment]
https://tetrabiodistributed.github.io/project-tetra-docs/papra-build-guide/components/building-tetra-papr-fan-box-v1/

**Comment by darraghbr** [comment]
@mechatroniks-git @DHHwangPhD 

![image](https://user-images.githubusercontent.com/31858409/107555594-42ea8480-6bcf-11eb-808e-dca3f935cbff.png)

When I tried to add the fan box PCB I got some clipping issues when I put it where I expect it to go. I am using the file in git called TypeA_PAPR2.

**Comment by mmroden** [comment]
the fan is upside down in this rendering, needs to be fitted

**Comment by darraghbr** [comment]
Turns out I was looking at the wrong version. Version to use is V4.2.

**Comment by darraghbr** [comment]
I've generated a milestone in Fusion. In Tetra PAPR\Archive\PAPRA V4\SinglePAPRv4 I've labelled it 'January version' is this the correct version of the assembly that was made in January? @DHHwangPhD  @mmroden

**Comment by mmroden** [comment]
that's the one from Jan 6th, so it could do in a pinch.  The next version used these parts: 
![_MMR0019-X2 fan box parts](https://user-images.githubusercontent.com/116251/108270512-6b6d0400-7124-11eb-9695-da63c9be38b4.jpg), which looks like it might be model 4.1 with the most recent top plate and a base plate missing

**Comment by darraghbr** [comment]
Are there still supports on the fan box outlet? I can't find a part that looks like that in any of the versions.

**Comment by mmroden** [comment]
Check the funnel in the part you mentioned: Tetra PAPR\Archive\PAPRA V4\SinglePAPRv4

<img width="374" alt="Screen Shot 2021-02-17 at 1 44 50 PM" src="https://user-images.githubusercontent.com/116251/108271881-52655280-7126-11eb-85cd-4cd353dddedb.png">

That would require supports

**Comment by darraghbr** [comment]
Yep that's all fine, I'm just trying to make sure I use the right version.

**Comment by mmroden** [comment]
gotcha.  I think the one we built had a part number on it, so it's not the one in that diagram; I think it's the same thing but with a part number.

**Comment by mmroden** [comment]
not really necessary for the milestone

**Comment by darraghbr** [comment]
solved in #82 ?

**Comment by mmroden** [comment]
No bandwidth, won't do
