### ISSUE TITLE
exploded diagram of the v2 of the m12 battery controller

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#29]
For these instructions:
https://tetrabiodistributed.github.io/project-tetra-docs/papra-build-guide/components/building-tetra-papr-m12-v2/

**Comment by mechatroniks-git** [comment]
Is this along the lines of what you want?
![image](https://user-images.githubusercontent.com/57600622/106033503-af6d6b80-6086-11eb-9822-4b1602a326e7.png)

**Comment by mmroden** [comment]
That would be great!  If we had the ability to label the various bits, that
would be an extra awesome step, but I realize that may be a bridge too far

**Comment by mechatroniks-git** [comment]
Or this? And image or pdf?

![image](https://user-images.githubusercontent.com/57600622/106037324-5fdd6e80-608b-11eb-974d-4e69bef1fef1.png)

**Comment by mmroden** [comment]
The second one is better; are the nuts not labeled because they are part of another part?

Image is great, pdf is a great addition, but image is the main deliverable I think.  PNG ideally, no jpg.

**Comment by mechatroniks-git** [comment]
Ok, the parts are grouped in assemblies, so you only get 1 number for the assembly, might be a way to do multi-level as a flat assembly, but will get all the board level parts. In any case, there is lots of cleanup to do on the files to have a part list that is correct. This will take some time.

**Comment by mmroden** [comment]
We probably need to do this for proper manufacturing handoff, I'd think.

**Comment by mechatroniks-git** [comment]
Yes, lots of busy work getting this done right. Assigning part numbers, updating each part's material property and part #, then the part's list will be good for exploded view drawings.

**Comment by darraghbr** [comment]
[A-TET-001102-0 M12 PAPRA Controller Drawing.pdf](https://github.com/tetrabiodistributed/papr-print-files/files/5961147/A-TET-001102-0.M12.PAPRA.Controller.Drawing.pdf)

Should be good to go @mmroden

**Comment by mmroden** [comment]
Perfect, got the fixed lid in there too!
