### ISSUE TITLE
P-TET-000112-0 DC Jack hole size too small

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#37]
Diameter too small for jack, open up to 8.4mm

![image](https://user-images.githubusercontent.com/57600622/106397441-51ac8c80-63c2-11eb-9e29-0758db7fc0a2.png)

**Comment by mmroden** [comment]
Should be fixed in the latest box, will put in a PR with the new fan box assembly

**Comment by mmroden** [comment]
Part of this work 
![image (25)](https://user-images.githubusercontent.com/116251/106787525-aa6b6780-6604-11eb-900a-4af71b76577f.png)
