### ISSUE TITLE
Funnel into lower box

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#4]
Difficult to mate funnel to box, fit is tight on PLA prints. 

Recommend adding chamfer lead edge & increase fit clearance.

**Comment by DHHwangPhD** [comment]
Edge has been chamfered.

**Comment by mmroden** [comment]
Part of this work, needs to be tested: 
![image (25)](https://user-images.githubusercontent.com/116251/106787576-ba834700-6604-11eb-96bf-1023ef957ed3.png)
