### ISSUE TITLE
m12 controller knob didn't fit

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#43]
The current controller knob didn't fit the potentiometer, could be a printer or material difference

**Comment by mechatroniks-git** [comment]
Print is good with PETG on Makerbot Rep 2. 

Issue can be fixed by printing at increased scale, adjust per printer 1-2% should suffice, part should work without problem with scaling +/-5% as the only critical feature is the 6mm knob shaft.
