### ISSUE TITLE
Funnel fit into box

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#5]
Funnel can be installed in 2 positions, only one way is correct.

**Comment by mmroden** [comment]
Prevented by the board being placed into the fan box
![image (25)](https://user-images.githubusercontent.com/116251/106787800-ff0ee280-6604-11eb-8932-d123bd7c8d91.png)

**Comment by mmroden** [comment]
Not yet tested, can't close yet
