### ISSUE TITLE
create mounting points as a separate STEP file

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#50]
the current mask (as of Feb 2021) with all the mounting points as separate bodies in the STEP file

**Comment by Burhan-Q** [comment]
@mmroden I don't have the mask with the filter mount that @DHHwangPhD made, so I don't have a way to upload that. The mounting points STEP file has been added to PR #60

**Comment by Burhan-Q** [comment]
@DHHwangPhD to added mask file
