### ISSUE TITLE
CPAP hose falls off of fan box fairly easily

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#53]
The hose fell off twice when wearing the PAPR to a park for three hours, which should not happen.

**Comment by darraghbr** [comment]
Perhaps a solution for the hoses coming off?

https://racesparesuk.com/product/brembo-reservoir-pipe-clip/

Could use a circlip and groove style of retention?

**Comment by mmroden** [comment]
Also test heat shrink on the tubing

**Comment by mmroden** [comment]
Will be solved by #14.  Silicone cuff seals are intended to be added/removed multiple times.
