### ISSUE TITLE
Document how fan boxes are tested

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#54]
with the portacount?

**Comment by mmroden** [comment]
repurposing sampling devices for this purpose
scoring in the range between N95 and N99
Daniel can help

**Comment by DHHwangPhD** [comment]
![image](https://user-images.githubusercontent.com/68876187/108606511-47e9c980-736f-11eb-8b40-167a1f3e8335.png)
We test by connecting the TSI PortaCount 8048 to the mask. We also test the box itself with the PortaCount.

**Comment by mmroden** [comment]
Can be solved with a video showing the portacount setup with the box.  Ideally showing both the box and mask testing setups, and would require test results for various boxes.

**Comment by mmroden** [comment]
Documented in the march docs
