### ISSUE TITLE
DC Jack on fan box is not sealed

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#56]
CUI DC Jack allows air to leak. Consider options for sealed unit.

Switchcraft L722RAS is IP68 rated, costs ~$5. Would require a board spin and bigger hole in the fan box.

![image](https://user-images.githubusercontent.com/57600622/107534002-5b798100-6b74-11eb-8442-e672dfb6d083.png)

**Comment by mechatroniks-git** [comment]
Straight version cheaper at newark: https://www.newark.com/switchcraft-conxall/pcl722as/connector-power-entry-jack-5a/dp/81R0092?CMP=AFC-OP

**Comment by mechatroniks-git** [comment]
@mmroden @DHHwangPhD I need to know if this is something I should proceed with. Do we need IP rated connectors? Should we look at something cheaper like this, that can be easier to seal (washer gasket and hot glue/silicone on the back)? https://www.newark.com/cliff-electronic-components/fc681473/dc-power-jack-1a-12vdc-panel/dp/08X1631

**Comment by mechatroniks-git** [comment]
Here is the L722RAS on existing PCB. Changes required
1. new PCB footprint
2. connector center height relative to PCB is taller, so to keep PCB in same location, hole on box moves 1.483mm. Also diameter increases to 11.8mm (was 8.8mm)

![image](https://user-images.githubusercontent.com/57600622/107683903-fe0a3080-6c56-11eb-9da4-7f9db21908a3.png)

**Comment by mmroden** [comment]
It is now sealed!

Testing two jan 9 units, n99 pass levels are:
1. 70
2. 80

Testing one Jan 31 unit, n99 pass level is:
1. 400

Testing three 13 March 2021 n99 pass levels:
1. 850  (24 particles)
2. 700 (30 particles)
3. 1200 (15 particles)
22k particles-- at these ratios, the numbers change a lot when a single particle is added or subtracted

But the new boxes are markedly better than the old

We do need better test hoses
