### ISSUE TITLE
Document different running and crossfit workout belts

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#59]
Testing different belts (molle, runner's belt) with running and crossfit

**Comment by mmroden** [comment]
Diana will be doing this work, Mark will record it

**Comment by mmroden** [comment]
Diana has a request for updates to the base plate
![Uploading To Mark.jpg…]()
![To Mark 3](https://user-images.githubusercontent.com/116251/108607024-ac5a5800-7372-11eb-965d-2131ca348b48.jpg)
![Uploading To Mark 2.jpg…]()

**Comment by mmroden** [comment]
More updates with jumping

![20210222_191709](https://user-images.githubusercontent.com/116251/109040179-7ecb2280-7682-11eb-9b4c-3a0c15b91932.jpg)
![20210222_191703](https://user-images.githubusercontent.com/116251/109040192-82f74000-7682-11eb-9df4-2909711d6057.jpg)

https://user-images.githubusercontent.com/116251/109040212-87bbf400-7682-11eb-970f-068b328ca8c0.mp4

**Comment by DHHwangPhD** [comment]
Lacing of webbing for securing the PAPR using the new MOLLE Adapter Short plates as well as securing the M12 controller.

![PXL_20210304_094745346](https://user-images.githubusercontent.com/68876187/110052097-d8c78a00-7d0b-11eb-8202-22b84c527409.jpg)
![PXL_20210304_094914355](https://user-images.githubusercontent.com/68876187/110052099-da914d80-7d0b-11eb-9126-e1ee8062e380.jpg)
![PXL_20210304_095239606](https://user-images.githubusercontent.com/68876187/110052100-da914d80-7d0b-11eb-9fda-c404122f2af2.jpg)
![PXL_20210304_094406906](https://user-images.githubusercontent.com/68876187/110052102-db29e400-7d0b-11eb-92ce-a452b8ba5924.jpg)
![PXL_20210304_094635720](https://user-images.githubusercontent.com/68876187/110052104-dbc27a80-7d0b-11eb-813f-4a9fc0ea4e83.jpg)

**Comment by mmroden** [comment]
Documentation is now in the march build
