### ISSUE TITLE
Base plate bowing

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#6]
When assembled, base plate exhibits bowing in the middle of the plate

**Comment by mmroden** [comment]
Fan is not actually at spec properly, will test things to solve the bowing-- contrary to the drawings, there's a .5mm change possible in the actual fan.

**Comment by mmroden** [comment]
@DHHwangPhD is looking this over

**Comment by mmroden** [comment]
Considered solved with the new molle plate
