### ISSUE TITLE
Exploded diagram for the Feb 2021 fan box

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#63]
now with the gasket for the funnel instead of the snap to fit

**Comment by darraghbr** [comment]
I tried to get the view from the other side but to no avail. I need an assembly number for this set up as well @mechatroniks-git 

[D-TET-0-0 Fan Box Drawing.pdf](https://github.com/tetrabiodistributed/papr-print-files/files/5998568/D-TET-0-0.Fan.Box.Drawing.pdf)

**Comment by mechatroniks-git** [comment]
Updates to parts list:
![image](https://user-images.githubusercontent.com/57600622/108598703-009a1380-7344-11eb-8262-794497292c96.png)

I prefer using tangent edges, shortened on the view
![image](https://user-images.githubusercontent.com/57600622/108598767-69818b80-7344-11eb-94b5-c0dfb140b2be.png)

**Comment by darraghbr** [comment]
Thanks Patrick, I have addressed your comments and given it an assembly number in this version.

[D-TET-001103-0 Fan Box Drawing.pdf](https://github.com/tetrabiodistributed/papr-print-files/files/6016193/D-TET-001103-0.Fan.Box.Drawing.pdf)

**Comment by mmroden** [comment]
Hole placement for the new fan controller board will likely need to be updated, but!  This is sufficient for assembly
