### ISSUE TITLE
Update the fan box for the new fan box power/controller board

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#65]
The fan power board with the airtight seal to the outside is a different part, need to update the box

**Comment by mechatroniks-git** [comment]
Ordered 3 each from OshPark to verify design changes. Expect boards back by March 13th (estimated, not a firm date). Will need to also order PCB parts to assemble board.

![image](https://user-images.githubusercontent.com/57600622/109043934-ab813900-7686-11eb-8837-74beba8fc467.png)

**Comment by mechatroniks-git** [comment]
@mmroden This delivery schedule will push the milestone date out to mid-March
