### ISSUE TITLE
Light pipes not captured, can fall off

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#7]
Light pipe is not fully secured to it's position and can fall out of the PCB

**Comment by mechatroniks-git** [comment]
@DHHwangPhD This looks good, not sure if you tested it, but might be better if you cheated the tab closer to the PCB, perhaps flush with the lower section?

![image](https://user-images.githubusercontent.com/57600622/105612539-bb4ceb00-5d71-11eb-8f43-2496ada45c8d.png)

**Comment by mmroden** [comment]
How will this get inserted?  The pressure fit is already tight, I'd be
worried about some alignment problem when it jams into place.

**Comment by DHHwangPhD** [comment]
![image](https://user-images.githubusercontent.com/68876187/105811968-3c6ad480-5f62-11eb-8294-bdf75ce56fdb.png)

Trying a clip style light pipe holder.

**Comment by mmroden** [comment]
![image (22)](https://user-images.githubusercontent.com/116251/106785854-bce4a180-6602-11eb-8f5b-66460ba1d590.png)
Closed by #31
