### ISSUE TITLE
Validate that fan box STLs have been properly constructed

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#71]
The Fan Box STLs have not been printing well on a prusa 3d.  @darraghbr thinks that there might be fan box issues

**Comment by mmroden** [comment]
![Uploading Image from iOS (5).jpg…]()

**Comment by mmroden** [comment]
[P-TET-000112-2 Fan Box_0.2mm_PLA_MK3S_8h12m.gcode.zip](https://github.com/tetrabiodistributed/papr-print-files/files/6037672/P-TET-000112-2.Fan.Box_0.2mm_PLA_MK3S_8h12m.gcode.zip)

**Comment by mmroden** [comment]
[P-TET-000112-2 Fan Box.3mf.zip](https://github.com/tetrabiodistributed/papr-print-files/files/6037679/P-TET-000112-2.Fan.Box.3mf.zip)

**Comment by Judoguy12** [comment]
Prints fine on my machine 
![Uploading PXL_20210225_170750243.MP.jpg…]()

**Comment by Judoguy12** [comment]
![PXL_20210225_170750243 MP](https://user-images.githubusercontent.com/30008485/109189599-1bc5b280-778c-11eb-9c0f-cf214c6832c6.jpg)

**Comment by mmroden** [comment]
Jamie can print it, I have problems
