### ISSUE TITLE
Orient STLs for proper printing

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#75]
Orient STLs so zero plane is print plane; right now, they are all over the place

**Comment by mmroden** [comment]
#74 gets us closer

**Comment by mechatroniks-git** [comment]
https://forums.autodesk.com/t5/fusion-360-design-validate/stl-exported-sideways/td-p/6718459

**Comment by mmroden** [comment]
To be done: respirator parts, fan box parts.  m12 is done from #74

**Comment by mmroden** [comment]
fan box cover (hex top) is not oriented properly

**Comment by mmroden** [comment]
fixed by #88 for mask and fan box

**Comment by mmroden** [comment]
Solved
