### ISSUE TITLE
Loose m12 controller lid

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/papr-print-files#76]
P-TET-000102-1 (a.k.a., m12 controller lid) seemed to be a loose fit when placed into the controller body
![PXL_20210226_030053387](https://user-images.githubusercontent.com/14095576/109345179-9b06c500-7824-11eb-805f-e13e4b4c9127.jpg)
![PXL_20210226_030106885](https://user-images.githubusercontent.com/14095576/109345191-9fcb7900-7824-11eb-8ceb-51cb16600f95.jpg)

**Comment by mechatroniks-git** [comment]
@capsulecorplab which revision of P-TET-000104 M12 Controller Body.stl did you print & test?

**Comment by mechatroniks-git** [comment]
I'll print P-TET-000102-1 and P-TET-000104-3 and test.

**Comment by mechatroniks-git** [comment]
![image](https://user-images.githubusercontent.com/57600622/109586699-93f8e480-7aba-11eb-88bf-b73c524c0bb8.jpeg)

Lid is held with friction only. It pops out easily when tapping the body. A positive lock would be better, perhaps the tabs can be longer and fit into grooves in the body?

**Comment by capsulecorplab** [comment]
@mechatroniks-git looks like you found it, but for the record, it was https://github.com/tetrabiodistributed/papr-print-files/commit/fd07e96a460faa9d1c7b4d5da6ee4366efcfc87a
