### ISSUE TITLE
M12 connector holes undersized

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/papr-print-files#8]
The holes for the DC power jacks and the on/off knob are undersized

**Comment by mechatroniks-git** [comment]
@DHHwangPhD  For standard part hole clearances in CNC, the following is a good guide:https://www.datametal.com/wp-content/uploads/2018/03/Metric-Tap-and-Clearance-Drill-Sizes.pdf

For CNC, you can get away with close-fit on holes, but for 3D printing, I wouldn't go tighter than standard fit. So the knob should be 7.7mm and the DC jacks should be 8.8mm (but also slotted left to right by +/-0.5mm).

![image](https://user-images.githubusercontent.com/57600622/105613158-c6097f00-5d75-11eb-81a5-eaea3b6c2c22.png)

![image](https://user-images.githubusercontent.com/57600622/105613151-af632800-5d75-11eb-9394-962172d94f0a.png)

**Comment by DHHwangPhD** [comment]
Updated the holes with 7.7 and 8.8 slots

**Comment by mmroden** [comment]
![image (23)](https://user-images.githubusercontent.com/116251/106786062-fae1c580-6602-11eb-8c0a-78597bd84b91.png)
closed by #31
