### ISSUE TITLE
How to waterproof/splashproof the papra?

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/papr-print-files#94]

**Comment by mechatroniks-git** [comment]
To make water-resistant, we would need to add seals to the housing, use the IP68 rated DC jack on the M12 PCB and add conformal coating on the PCBA. https://www.mgchemicals.com/products/conformal-coating/silicone-conformal-coatings/silicone-modified-conformal-coating/

**Comment by mmroden** [comment]
Goal is splashproof/Englandproof.  Not for direct rainshowers, but for mist/running use cases.  Will be closed by #102, #103, #105

**Comment by mmroden** [comment]
closed by #113, but needs to be tested
