### ISSUE TITLE
Adapter for different size jack holes in the fan box

### ISSUE THREAD

**Issue by DHHwangPhD** [tetrabiodistributed/papr-print-files#95]
Previous non IP rated jack is smaller than the sealed jack. The sealed jack is larger. Need an adapter that reduces the hole size so the current fan box can use the older board/jack.

**Comment by DHHwangPhD** [comment]
Stopgap plan.

**Comment by DHHwangPhD** [comment]
We need this to make the march build work; in the end, the papra-pcb issue of not having the proper cable for the dust-proof connector needs to be solved.

**Comment by mmroden** [comment]
Closing as not to be done; ended up doing connectors as spec'd.  The STL exists and we built it, but it's not a good idea.
