### ISSUE TITLE
Fan box jack issues

### ISSUE THREAD

**Issue by DHHwangPhD** [tetrabiodistributed/papr-print-files#96]
Problems with the power jack in the fan box.
Original power jack for the board is not sealed.
New power jack is sealed, but will require custom cables.
Other jacks like M12 have been discussed with @mechatroniks-git

**Comment by darraghbr** [comment]
Can you expand on why you think the new connector needs a custom cable? The jack is for a standard 5.5 mm x 2 mm plug.

**Comment by mechatroniks-git** [comment]
The connector entry is deeper and has an oring seal, so the cable end needs to be longer and match the diameter at the seal

**Comment by mmroden** [comment]
yeah @darraghbr-- @mechatroniks-git had to sand down a connector to make a custom connector for a cable.  So either we need another jack or we need custom cables.

**Comment by darraghbr** [comment]
By the looks of things the compatible jack uses a thread to pull the 2 parts together to create a seal.

https://www.mouser.co.uk/ProductDetail/Switchcraft/S761KS15?qs=fbkhFuCHoTam5cvHIFHKsw%3D%3D

**Comment by mechatroniks-git** [comment]
![image](https://user-images.githubusercontent.com/57600622/111810479-47bbeb80-8893-11eb-986c-df7e9cf01348.png)
BNC Cable: https://www.monoprice.com/product?p_id=16180
BNC Connector: https://www.digikey.com/en/products/detail/adam-tech/RF1-01A-D-00-75-M/9831054

**Comment by mmroden** [comment]
Will likely close if the BNC connector route works: #102
